#!/bin/bash
#SBATCH --job-name=train_phn_extended_residual_plots_32
#SBATCH --account=sk54
#SBATCH --time=24:00:00
#SBATCH --partition=gpu
#SBATCH --ntasks=6
#SBATCH --gres=gpu:1
#SBATCH --mem=60G

#SBATCH --mail-user=weihao.li@monash.edu
#SBATCH --mail-type=BEGIN,END,FAIL

source ~/.bashrc
conda activate tf
module load R/4.0.5

cd ~/sk54/patrickli/auto_residual_reading
python scripts/training/phn_extended_residual_plots_32.py


